[project]
name = "TwinCAT_container_monitor"
version = "0.1.0"
description = "Beckhoff Automation K.K."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyads",
    "plotly",
    "pandas",
    "streamlit"
]

